#CONFIG FOR FE PART
version: 2.1
workflows:
    frontend-workflow:
        jobs:
            - build:
                  context:
                      - montechristo-env-vars

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                  echo "$DOCKERHUB_PASSWORD" | docker login --username kostnerek --password-stdin

            # build the application image
            - run: docker build -f Dockerfile.client -t kostnerek/montechristo-fe .

            # deploy the image
            - run: docker push kostnerek/montechristo-fe
            - add_ssh_keys:
                  fingerprints:
                      - "6b:80:4c:3c:63:3f:43:89:87:d6:45:fc:8f:9d:2d:74"
            - run: |
                  ssh -o "StrictHostKeyChecking=no" lema@20.222.251.245 \<<'ENDSSH' 
                  sudo docker pull kostnerek/montechristo-fe
                  sudo docker kill nginx_client_1
                  sudo docker kill nginx_api_1
                  sudo docker-compose -f /home/lema/docker-compose.yml up
                  ENDSSH
