version: 2.1
workflows:
    my-workflow:
        jobs:
            - build:
                  context:
                      - montechristo-env-vars

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                  echo "$DOCKERHUB_PASSWORD" | docker login --username kostnerek --password-stdin
                  docker run -d --name montechristo kostnerek/montechristo-fe

            # build the application image
            - run: docker build -t kostnerek/montechristo-fe .

            # deploy the image
            - run: docker push kostnerek/montechristo
            - add_ssh_keys:
                  fingerprints:
                      - "04:f8:a5:21:e4:db:78:be:53:20:be:7c:d0:b3:8e:12"
            - run: |
                  ls /home/circleci/.ssh
            - run: |
                  ssh lema@20.222.251.245 \<<'ENDSSH' 
                  sudo docker pull kostnerek/montechristo
                  sudo docker stop montechristo
                  sudo docker rm montechristo
                  sudo docker run --name montechristo -p 80:80 -d kostnerek/montechristo
                  ENDSSH
